### ISSUE TITLE
This line only works in .vim files

### ISSUE THREAD

**Issue by reverseila** [wincent/wincent#118]
I'm not sure why this bit of code works in .vim files and not in anything else.

https://github.com/wincent/wincent/blob/4e2e685628b778ae197c9f64c39425d03b09925f/aspects/nvim/files/.config/nvim/init.lua#L142

I took it from one of your [videos](https://youtu.be/mhP0aSDOIY4?t=991). So what I have in my set up is:
```vim
vim.opt.textwidth = 79
vim.opt_local.colorcolumn = '+' .. vim.fn.join(vim.fn.range(0,254), ',+')
```

**Comment by reverseila** [comment]
I made a mistake. Instead of setting 'textwidth' to 79 I set 'colorcolumn' to 79. Sorry for the noise.

**Comment by wincent** [comment]
Yep, those `+` values are relative to the `textwidth`.
