### ISSUE TITLE
Undefined global key

### ISSUE THREAD

**Issue by kdheepak** [wincent/wincent#119]
`key` is undefined at this line:

https://github.com/wincent/wincent/blob/d183dbd5065bc65b5b829868250ce149f26a8cac/aspects/nvim/files/.config/nvim/lua/wincent/vim/map.lua#L32

because `key` is local to the `if` block here:

https://github.com/wincent/wincent/blob/d183dbd5065bc65b5b829868250ce149f26a8cac/aspects/nvim/files/.config/nvim/lua/wincent/vim/map.lua#L10-L16

To fix this, you can add `local key` before the `if` block and remove the `local` keyword in the `if` block, i.e.:

```lua
  local rhs_type = type(rhs)
  local key
  if rhs_type == 'function' then
    key = wincent.util.get_key_for_fn(rhs, wincent.g.map_callbacks)
    wincent.g.map_callbacks[key] = rhs
    rhs = 'v:lua.wincent.g.map_callbacks.' .. key .. '()'
  elseif rhs_type ~= 'string' then
    error('map(): unsupported rhs type: ' .. rhs_type)
  end
```

**Comment by wincent** [comment]
Thanks @kdheepak. Good catch. I'm not calling this function from anywhere so hadn't noticed it was busted.

**Comment by kdheepak** [comment]
No worries! Thanks for making all this public! It’s been an excellent resource!
