### ISSUE TITLE
E117: Unknown function: <SNR>140_CheckColorScheme

### ISSUE THREAD

**Issue by albasili** [wincent/wincent#120]
https://github.com/wincent/wincent/blob/a977bd6a499332254ededf732c3d71c04315f216/aspects/nvim/files/.config/nvim/after/plugin/color.vim#L98

I've been inspired by your dotfiles and screencasts for many years and I shamelessly copy several bits and pieces of your repo. Recently I changed job and sure enough I had to struggle to get my dotfiles back in place.

One issue that I recently found is that when launching vim ( 8.0) I get this error:
```E117: Unknown function: <SNR>140_CheckColorScheme```

which it's kind of strange cause the function is in the same file. If I try to call the function after startup is over than everything goes as expected. Would you have any idea why is that so? Any pointer is helpful.

Thanks!

**Comment by wincent** [comment]
Well that is rather odd, isn't it? I don't actually know. One thing you could do is switch it from being a script-local function to a globally-visible one. ie. just delete the `s:` from the definition and the call-sites (feel free to rename the function too, if you want to "namespace" it in some way so as to avoid a potential name collision with something else).

For a few years now, I haven't been testing anything in Vim (using Neovim full-time, basically), so I wonder if this is a Vim-specific thing — at the current `HEAD` of the `main` branch, the `~/.vim/after/plugin/color.vim` file doesn't even exist anymore...

**Comment by albasili** [comment]
Indeed giving it global visibility helps! Thanks a lot, and although i'm not keen to move to neovim your workflow will always be a good source of inspiration.
