### ISSUE TITLE
use Docker

### ISSUE THREAD

**Issue by SingularisArt** [wincent/wincent#122]
Hello.

I was wondering if you could add a Dockerfile for those who want to try out your dotfiles, but don't want to remove their entire setup.
It's just an idea. If you want, I could make it for you, but if you don't see this idea fitting, then please remove this issue.

Thanks

**Comment by wincent** [comment]
Yeah, I don't see any harm in adding a Dockerfile — although I am too much of a Docker noob to actually produce one myself.

I've always felt that dotfiles are best stolen from, piece by piece, and not copied wholesale — but I can also see the value in being able to just try out the whole thing together in an isolated environment.

**Comment by SingularisArt** [comment]
Great! I'll see if I can create a Dockerfile and then create a pull request!
