### ISSUE TITLE
Mutt

### ISSUE THREAD

**Issue by SingularisArt** [wincent/wincent#124]
Hello.

I know you got rid of mutt, but how can I use your mutt configuration? I saw your videos about mutt and I really like your configuration.
Could you please elaborate on how I would use your mutt configuration?

Thanks

**Comment by wincent** [comment]
You could look at [the repo as it existed](https://github.com/wincent/wincent/tree/cfc2958b08b0a2c33d3785746b71f4ab1f3f1984) before commit 2020062590cbdba792fe1b419c3bb754c0da649e, where I removed (almost all of) the mutt config.

**Comment by SingularisArt** [comment]
Great! Thanks.

May I ask why you got rid of **mutt**?

**Comment by wincent** [comment]
It's in [the commit message](https://github.com/wincent/wincent/commit/2020062590cbdba792fe1b419c3bb754c0da649e) above.
