### ISSUE TITLE
Use termguicolors when available

### ISSUE THREAD

**Issue by wincent** [wincent/wincent#17]
MacVim:

<img width="690" alt="install____code_wincent__-_vim_and_new_issue_ _wincent_wincent" src="https://cloud.githubusercontent.com/assets/7074/15173616/ec480df8-1711-11e6-9818-39145b9deb4e.png">

With `'termguicolors'`:

<img width="704" alt="vim___glh-mbp___masochist___zsh__tmux_" src="https://cloud.githubusercontent.com/assets/7074/15173588/c23fc2b2-1711-11e6-86bd-7ba6df3c3501.png">

Without `'termguicolors'`:

<img width="704" alt="vim___glh-mbp___masochist___zsh__tmux_" src="https://cloud.githubusercontent.com/assets/7074/15173649/1389080e-1712-11e6-85dc-e93a691bb5f4.png">

**Comment by lencioni** [comment]
Were you able to resolve the different black background behind the text when `termguicolors` is enabled?

**Comment by wincent** [comment]
Needed [this](https://github.com/wincent/wincent/commit/25f014528f22de421973c5a8d0fe17329add2b91#diff-6e0c2470d5a5a0088df0b45cb28076a2R98) in order to resolve it.

**Comment by wincent** [comment]
Also, follow-ups: 68352a69ef10d3d (fixes some weirdness with named colors like "Red") and 99b0f5b6024ca9d03c (just hygiene).
