### ISSUE TITLE
Colors script doesn't work anymore since base16-shell update

### ISSUE THREAD

**Issue by OkanEsen** [wincent/wincent#18]
The color schemes for base16-shell were updated two days ago and caused to break the colors script.

**Comment by wincent** [comment]
Thanks for the heads up. I'll be sure to check out what changed before changing the submodule.

**Comment by wincent** [comment]
I had a look at the changes and left some feedback [here](https://github.com/chriskempson/base16/issues/42#issuecomment-229958109). Unfortunately this is a bit of a breaking change, so I might wait until the dust has settled and all/most/many of the light schemes are back in the repo.

**Comment by lencioni** [comment]
I solved this by extracting the background color from the theme and calculating its luma, which is a measure of perceptual lightness. https://github.com/lencioni/dotfiles/commit/f8a65296e72183bcd6c5b845a0556e6110019c77

**Comment by wincent** [comment]
@lencioni. Nuts!

Still waiting for the schemes I actually use to be made available in light variants. Otherwise not much point in "upgrading" yet.

You crazy, Joe.

**Comment by codybuell** [comment]
@lencioni Awesome workaround!  You mentioned in your commit that the base16 shell files are no longer executable, take a look [here](https://github.com/codybuell/dotfiles/blob/master/dotfiles/shell/color#L71-L73) for one solution.
