### ISSUE TITLE
Status line question

### ISSUE THREAD

**Issue by LikiPiki** [wincent/wincent#19]
I would like to put your status line in my vim config.
I paste https://github.com/wincent/wincent/blob/master/roles/dotfiles/files/.vim/autoload/statusline.vim statusline.vim in autoload folder and https://github.com/wincent/wincent/blob/master/roles/dotfiles/files/.vim/plugin/statusline.vim in plugin folder. I set base16 tommorow dark colortheme into iterm and vim, but status line have not colors.
How to fix this? 

![2016-07-01 21 43 10](https://cloud.githubusercontent.com/assets/8510866/16531549/92fd81e6-3fd5-11e6-816c-3fff0ea2f726.png)

**Comment by wincent** [comment]
Have you got the pinnacle plug-in installed? We rely on that [to set up the colors](https://github.com/wincent/wincent/blob/a4f1e80cb504099464b0d9850bfd76bb099ce613/roles/dotfiles/files/.vim/autoload/statusline.vim#L48).

**Comment by LikiPiki** [comment]
Ok, thanks a lot.
