### ISSUE TITLE
Color is not working on my vim

### ISSUE THREAD

**Issue by victorvoid** [wincent/wincent#20]
=( after installing:

![screenshot from 2016-07-31 19 33 28](https://cloud.githubusercontent.com/assets/6734111/17280096/ba8c64ec-5755-11e6-8664-8519c6b6cde7.png)

terminator
Can you help me ?

**Comment by wincent** [comment]
I don't really have any recent experience on other platforms. Is this the Gnome Terminator thing? Are the colors only screwed up inside Vim, or everywhere in the terminal?

**Comment by VictorVoid** [comment]
Yes, I use gnome on ElementaryOS, but Terminator and Gnome Terminal has this error, tmux is very nice, base 16 beautiful and has no error, just in the vim. Recommends another terminal for Linux? Or how to fix this? =( Your dotfiles is very nice =) I saw on your youtube channel, thanks.

**Comment by wincent** [comment]
Not really sure. You might have to dig into it and try a few different things. If you can figure out what is going wrong and how to fix it I'd be happy to incorporate the solution (or document it) in this repo.

**Comment by wincent** [comment]
I recently updated the color stuff to work on top of the latest version of the upstream base16 repos, so this is very likely stale at this point. Feel free to comment if you think it should be reopened.

**Comment by lookeme** [comment]
I have the same issue on macOs Sierra 10.12.2. Something wrong with  vim and tmux. But when I  open mvim there is everything is fine. Any ideas?

**Comment by lookeme** [comment]
<img width="1440" alt="screen shot 2017-01-18 at 08 37 48" src="https://cloud.githubusercontent.com/assets/9050898/22052318/84cc6ee8-dd5a-11e6-84a6-393785efe260.png">

**Comment by lookeme** [comment]
<img width="1440" alt="screen shot 2017-01-18 at 08 41 32" src="https://cloud.githubusercontent.com/assets/9050898/22052331/8dfe0fe4-dd5a-11e6-8e2b-2e0af04bac2a.png">

**Comment by wincent** [comment]
@lookeme: I think this is unlikely to work in Terminal.app. You could try testing it in iTerm (preferably a recent version).

**Comment by lookeme** [comment]
Indeed! Thanks a lot!
