### ISSUE TITLE
Suggestion for toggling trailing whitespace listchar

### ISSUE THREAD

**Issue by RatanRSur** [wincent/wincent#22]
I'm not sure if you would like this but I took your listchar setup and added this:

```
autocmd InsertEnter * set listchars-=trail:•
autocmd InsertLeave * set listchars+=trail:•
```

You're probably used to them showing up in insert mode now but I found it very unintuitive. I don't really think of a space as "trailing" until it's sitting there in normal mode.

**Comment by wincent** [comment]
You're right that I am very used to the opposite thing happening here, but I still think this is a neat idea. I'll probably give it a try.

**Comment by wincent** [comment]
Thanks for the suggestion, @RatanRSur. I took this for a spin a couple of times, but couldn't get used to it in the end. Great idea though. Going to close this for now as I don't think there's anything more actionable for me to do.

**Comment by RatanRSur** [comment]
Cool, I'm glad I could suggest something to you since your vimcasts have suggested so much to me :)
