### ISSUE TITLE
Error when using tmux

### ISSUE THREAD

**Issue by HieuNM6** [wincent/wincent#23]
Setting `unbind-key -t vi-copy MouseDragEnd1Pane` line 86 in .tmux.conf it look like not working on Linux environment (Ubuntu 16.04).

**Comment by wincent** [comment]
The version of tmux you're using is probably too old. The drag-end stuff was only recently added, and there is no way to do conditional checks (ie. version checks) inside the config file to prevent old versions from complaining about unknown settings.

**Comment by lencioni** [comment]
[The required minimum version is documented in the readme](https://github.com/wincent/wincent#dependencies).

**Comment by HieuNM6** [comment]
Thanks, I was updated Tmux and the error was gone
