### ISSUE TITLE
how could i change the vim color when the shell changed

### ISSUE THREAD

**Issue by machenchi0207** [wincent/wincent#24]
i use your colors shell script and it works well.i saw your youtube video that show it can change both of vim and shell color.i find that color.vim in after/plugin and move it to my .vim/after/plugin.so when i type 'color dark tomorrow' in the iterm2 shell and it works in the shell.but the vim didn't change its color.
finally,i reopen the vim with 'vim' in the shell  and the vim changed to the dark tomorrow.

so,how can i make it like the video you have done? many thanx.

**Comment by wincent** [comment]
[This line](https://github.com/wincent/wincent/blob/23c417ee4dbf713f666a2c41b1df8fca361d081b/roles/dotfiles/files/.vim/after/plugin/color.vim#L39) is what is supposed to trigger the update. You are likely not getting `FocusGained` events. One way to get them is via [the Terminus plug-in](https://github.com/wincent/terminus) (depends on your terminal capabilities, but iTerm, for example, works).

**Comment by machenchi0207** [comment]
i install the wincent/terminus plugin with vundle.
but how could i make it work?

**Comment by wincent** [comment]
Hm, not sure about Neovim. At least in normal Vim, Terminus just works without any special configuration.

**Comment by machenchi0207** [comment]
ok.i remove the neovim and install vim 8.0.it works in iterm2 with vim.but dose not work in tumx .........

**Comment by wincent** [comment]
Should work in tmux. What version of tmux and iTerm are you using?

Note that in iTerm under the "Advanced" section of the preferences there is a setting, "Apps may turn on Focus Reporting", that should be set to "Yes". I don't remember if this is on by default or not.

**Comment by machenchi0207** [comment]
hoops,it works now.even the color theme has some litter problem.but thanks a lot.
