### ISSUE TITLE
Getting E254: Cannot allocate color

### ISSUE THREAD

**Issue by xkef** [wincent/wincent#34]
Installed with ./install in fresh macos sierra virtual machine.

Starting vim from iTerm gives the following error:

Error detected while processing function statusline#update_highlight:
line   27:
E254: Cannot allocate color guibg=#a7adba
E254: Cannot allocate color guibg=#a7adba

The color code depends on the color scheme loaded, which here corresponds to the base16-ocean
 let g:terminal_color_12 = "#a7adba".

I am using the newest stable iTerm2 where "echo $TERM" gives "xterm-256color".

**Comment by wincent** [comment]
Wondering if this is related: http://stackoverflow.com/questions/37032181/launching-macvim-gives-e254-cannot-allocate-color

**Comment by xkef** [comment]
don't see how unfortunately as I am not using macvim although a much newer version is installed.

**Comment by xkef** [comment]
Okay, got it to work. Deleting the repo, cloning again and manually installing command-t and ycm works for me. Somehow running "./install vim" produces the error.
