### ISSUE TITLE
Recommend optimal locale settings for Linux in README?

### ISSUE THREAD

**Issue by zacacollier** [wincent/wincent#35]
I recently tried to pull down these configs on a fresh Arch Linux install but I experienced some erratic behavior / artifacts in my terminal. Tab-completion of files directories would cut into the prompt and corrupt the contents on the command line.

I gathered from reading [this StackOverflow answer](http://stackoverflow.com/a/30479702/6572258) that it had to do with a bad `locale.conf` on my part - improperly setting `LC_CTYPE=C` - as I experienced issues elsewhere with Powerline, and ended up working around it by explicitly setting UTF-8 in my `.zshrc`. 

I'm going to give it another shot after I update all `LC_*` variables to UTF-8 and report back with my results. Assuming that was the culprit, might be worth a mention in the README (I'd be happy to submit it if so). Also possibly a due consideration going forward in #7.

**Comment by wincent** [comment]
> I'm going to give it another shot after I update all `LC_*` variables to UTF-8 and report back with my results. Assuming that was the culprit, might be worth a mention in the README (I'd be happy to submit it if so).

Sure. I'd be happy to incorporate a PR. FWIW, the only Linux box I use these dotfiles on happens to work out-of-the-box, but that's a CentOS machine.

**Comment by zacacollier** [comment]
Installation went well this time - as suspected, I had to manually set `LC_*` variables in order for the zsh configs to work out of the box. #46 documents this caveat in the README.
