### ISSUE TITLE
Consider dropping buffer number from statusline

### ISSUE THREAD

**Issue by wincent** [wincent/wincent#38]
Two data points from colleagues. Saw one colleague do it and like, saw another get confused by it. Not sure whether this is something I'll like.

**Comment by lencioni** [comment]
Drop it, it's not valuable enough for the real estate it occupies.

**Comment by wincent** [comment]
Indeed, you are the "one colleague" I was referring to above who liked this. I'm still not sure though. I actually like having a visual reminder of how long my Vim instance has been running, and I like the aesthetics of having a column that lines up with the line numbers in the left gutter; if I removed the buffer number, I would want to put something else (more valuable) in that space, but I am not sure what exactly (modified flag? something else?).

**Comment by lencioni** [comment]
Clear your interface and clear your mind.

**Comment by wincent** [comment]
Ok, I think I've been able to trim it down to this:

<img width="720" alt="vi__vim_" src="https://cloud.githubusercontent.com/assets/7074/25242507/c55ccc40-25ae-11e7-9ffd-fa0fb72384c1.png">

`set shortmess+=I` and I should be good to go. Now if only I could figure out how to not draw those `EndOfBuffer` characters. Maybe just set them so that foreground color equals background color?

**Comment by lencioni** [comment]
🍭
