### ISSUE TITLE
Return events get eaten after a while

### ISSUE THREAD

**Issue by wincent** [wincent/wincent#47]
I don't know exactly when this started — it was either a Hammerspoon or a macOS upgrade — but I started seeing "return" keypresses get eaten a while back (some time within the last couple of months).

I wanted to add some logging to Hammerspoon to troubleshoot it, but — you guessed it — restarting Hammerspoon in order to activate the logging also fixed the issue. I had this happening reliably whenever I did a fast rollover like `git st<CR>`; basically that `<CR>` would get eaten and I'd have to do a separate `<CR>` down and up in order to run the command. I could repro it with 100% success. Added the logging, reloaded the Hammerspoon config (didn't even restart it) and the problem was gone.

So I may have to try and solve this by sheer logic and reasoning alone. Or I can add logging specific to the return key and just let it log for hours until the issue starts to manifest alone.

It is possible that there is no bug in the `eventtap.lua` module and it's the OS itself that is swallowing events. (For example, there could be some kind of queue or something that is getting full, and reloading the Hammerspoon process ends up freeing some port and draining or resetting the queue.) But regardless of where the bug lies, I need to come up with a mitigation because this is so darn annoying.

**Comment by GrigoryPtashko** [comment]
I've started using your configs about half a year ago. I made a fork since not everything works on os x el capitan and a macbook pro mid '11. But I'm merging your upstream on a regular basis. And sometime ago I've also noticed this issue. The Enter really gets eaten somehow. I confirm! I thought it is something with my system but I've found this post in my inbox : ) (I'm watching your repo)

**Comment by wincent** [comment]
I've added some more logging to try and catch this in the act, but it hasn't happened for me since I added the logging... sigh. In any case, restarting Hammerspoon always fixes it. I expect it to be a Hammerspoon issue or a macOS issue caused by a version change in one of the two, but I am hopeful that I can implement some sort of heuristic to work around it if only I can catch it happening and get some good log data...

**Comment by wincent** [comment]
Karabiner Elements is now good enough to mostly replace the Hammerspoon stuff (see https://github.com/wincent/wincent/commit/198654687c7f9391a2b961049194c39ac1197f8b) so I am going to close this.

**Comment by wincent** [comment]
And I am still seeing it even with Karabiner Elements... So something fishy is going on...
