### ISSUE TITLE
Check config with ansible-lint

### ISSUE THREAD

**Issue by wincent** [wincent/wincent#49]
https://github.com/willthames/ansible-lint

**Comment by cadens07** [comment]
Hi !
I get a fatal error during the full install, I have this message :
----------------------------------------
Fatal: [localhost]: FAILED! => {
    "changed": true, 
    "cmd": [
        "/home/xxxxxxxx/wincent/roles/dotfiles/support/karabiner-test.js"
    ], 
    "delta": "0:00:00.470693", 
    "end": "2019-08-24 21:02:02.314613", 
    "invocation": {
        "module_args": {
            "_raw_params": "/home/xxxxxxxx/wincent/roles/dotfiles/support/karabiner-test.js", 
            "_uses_shell": false, 
            "argv": null, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "stdin": null, 
            "warn": true
        }
    }, 
    "msg": "non-zero return code", 
    "rc": 127, 
    "start": "2019-08-24 21:02:01.843920", 
    "stderr": "/usr/bin/env: ‘node’: No such file or directory", 
    "stderr_lines": [
        "/usr/bin/env: ‘node’: No such file or directory"
    ], 
    "stdout": "", 
    "stdout_lines": []
}
	to retry, use: --limit @/home/xxxxxxxxx/.ansible/linux.retry
-----------------
Im on Manjaro xfce. any idea ?

thanks

**Comment by wincent** [comment]
@cadens07: I copied this into a new issue and will reply there: https://github.com/wincent/wincent/issues/79
