### ISSUE TITLE
Ansible error after merging with upstream

### ISSUE THREAD

**Issue by GrigoryPtashko** [wincent/wincent#51]
Hello!

I've merged upstream/master today and running `install` or `install -f` immediately after `sudo password` gives the following output:

```console
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/Users/macbook/wincent/roles/vim/tasks/main.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- import_tasks: bundle.yml
  ^ here


The error appears to have been in '/Users/macbook/wincent/roles/vim/tasks/main.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- import_tasks: bundle.yml
  ^ here
```

How can I fix this?

**Comment by wincent** [comment]
You probably just need "git submodule update" (not sure if you need "--recurse" or "--recursive" or something as well: I'm on my phone).

**Comment by GrigoryPtashko** [comment]
Done that. The error remains. `git submodule status` gives among other submodules the following

```console
 cdec853e37d2342346f54e51f4ec4bfbd2ee0031 vendor/ansible (v2.2.0.0-1)
```

Can this be the cause?

**Comment by wincent** [comment]
That looks like the wrong rev. It's supposed to be pointed at https://github.com/ansible/ansible/tree/bf43eb92f50ea8edc9e7b704ef91b3121ec972f0

Ansible deprecated the old "include" directive in favor of "import_tasks" (and "include_tasks", if I recall correctly), so until you update the Ansible submodule I expect you'll continue to see that error.

**Comment by GrigoryPtashko** [comment]
I added `branch=devel` to `.gitmodules`, then `git submodule update -- remote` and the `./install -f` worked. I guess I'm not that good at `git`.
Anyways, thanks.

PS I'm in the middle of your vim screencasts. After half a year of using your dotfiles they are a great addition! Thank you for such a great work!

**Comment by wincent** [comment]
Glad to hear you got it sorted out (although surprised it didn't just work the first time!).
