### ISSUE TITLE
Ctrl-I stopped working as 'back' in vim

### ISSUE THREAD

**Issue by GrigoryPtashko** [wincent/wincent#52]
After the latest merge with `upstream/master` the Ctrl-I mapping stopped working as it was. Now it's acting as the TAB key again in vim.
How can I diagnose this issue?
I've got Hammerspoon launched, btw.

**Comment by wincent** [comment]
I removed the Hammerspoon configuration, replacing it with Karabiner-Elements in https://github.com/wincent/wincent/commit/198654687c7f9391a2b961049194c39ac1197f8b

Karabiner-Elements recently acquired enough features to do this, and it operates more reliably than Hammerspoon for this kind of thing.

Closing as I think this should be enough for you to resolve your issue, but let me know if you have any other questions/comments etc.
