### ISSUE TITLE
Statusbar question

### ISSUE THREAD

**Issue by danmcatee** [wincent/wincent#58]
Hi i added your statusbar and it doesnt show up colored until i explicitly source my vimrc file
Any clues?

**Comment by wincent** [comment]
Not enough info to debug. Do you have a link to your dotfiles?

**Comment by danmcatee** [comment]
https://gist.github.com/danmcatee/e14a0e1d3031a386b1ce948ebcfbb710

**Comment by wincent** [comment]
I suspect you're going to need something like this too: https://github.com/wincent/wincent/blob/master/roles/dotfiles/files/.vim/plugin/statusline.vim (maybe you already have it, but I don't see it in the gist).

**Comment by wincent** [comment]
More than 30 days without activity, so going to close this one.
