### ISSUE TITLE
tmux is behaving strangely

### ISSUE THREAD

**Issue by roguearch** [wincent/wincent#59]
Hi, i am a newbie for vim and tmux environment. I am using this repository files. And when i switch to tmux, terminal is behaving strangely. Can't delete, and when i typing there is non-sense characters.

![](https://im4.ezgif.com/tmp/ezgif-4-ba672aab94.gif)

**Comment by wincent** [comment]
Not enough info here to troubleshoot. Try starting with an empty `~/.tmux.conf` (or one with everything commented out) and gradually re-enable things until you discover what is causing the problem.

**Comment by roguearch** [comment]
Hi, i checked .tmux.conf file line by line and when i disable this code line, everything is fine
`set -g default-terminal "tmux-256color"`
then i set this line to this
`set -g default-terminal "xterm-256color"`
and i just wondering, does this change cause a problem?

**Comment by wincent** [comment]
Your terminfo database probably doesn't have a `tmux-256color` entry.

**Comment by roguearch** [comment]
i think i am using with xterm-256color thank you
