### ISSUE TITLE
Airline theme

### ISSUE THREAD

**Issue by LikiPiki** [wincent/wincent#6]
Sorry again((
What theme for airline(powerline) you use in image
https://raw.githubusercontent.com/wincent/wincent/media/screenshot.png

**Comment by wincent** [comment]
It's not actually a theme. It's just a normal statusline that happens to use the Powerline triangle glyphs. It gradually evolved to this point, and I never felt the need to full in a heavy-weight plug-in for this purpose.

It's defined [here](https://github.com/wincent/wincent/blob/master/roles/dotfiles/files/.vim/plugin/statusline.vim).

It relies on some logic [here](https://github.com/wincent/wincent/blob/master/roles/dotfiles/files/.vim/autoload/statusline.vim) for various things.

Of particular interest (to me) is that it does [some custom stuff](https://github.com/wincent/wincent/blob/cceff0a04b790a6f1a6ce74d5e792605597dd470/roles/dotfiles/files/.vim/autoload/autocmds.vim#L28-L82) to tone down the status line for all windows except the current one. (Relatedly, [some other tweaks](https://github.com/wincent/wincent/blob/cceff0a04b790a6f1a6ce74d5e792605597dd470/roles/dotfiles/files/.vim/plugin/autocmds.vim#L14-L25) are applied to make these non-focused windows recede into the background.)

**Comment by LikiPiki** [comment]
Thanks a lot
