### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by mehmetcanbudak** [wincent/wincent#66]
<img width="1920" alt="screen shot 2018-05-31 at 8 34 19 am" src="https://user-images.githubusercontent.com/18473037/40763444-997f5900-64ad-11e8-88f0-0aeb644e7500.png">

**Comment by wincent** [comment]
You could try fetching the URL that it is complaining about with `curl` and see if that shows the same SSL error.

**Comment by mehmetcanbudak** [comment]
I get this.
<img width="1920" alt="screen shot 2018-05-31 at 8 47 55 am" src="https://user-images.githubusercontent.com/18473037/40763915-685c9f66-64af-11e8-8cad-10a4f1f66641.png">
