### ISSUE TITLE
terminal color switching using base16

### ISSUE THREAD

**Issue by damnskippy** [wincent/wincent#70]
This is more of a question (than an issue) regarding usage of color function to change the terminal base16-shell color theme, in a TMUX session *with multiple windows*.
(BTW, this whole idea behind the dark/light determination and dynamic switching is stupendous!).

When the terminal theme is switched by doing a `color <theme>`, if the TMUX session has multiple tmux "windows", the color change seems to take effect only in the current/active window, other tmux windows continue with the old/previous theme.  I think this behavior makes sense as this seems to be achieved by sending esacpe sequences to the terminal.  (FWIW I'm using gnome-terminal on linux (ubuntu).)

My question is do you also see the same behavior?  Or am I missing a trick somewhere to change other tmux windows as well?  Or it's possible I'm doing something wrong in my conf files somewhere to cause this for myself.  So I just thought I'd check with you just in case.

(I guess I could do a list-windows/panes for the session and do a send-keys of the color command, but I'm a bit wary about typing keys somewhat arbitrarily into a pane.  Maybe I could open a new temporary pane and run this command and close the pane when done..)

Thank you.

**Comment by wincent** [comment]
Yep. This is expected. I considered it an acceptable compromise because I switch colors rarely. But I do think it would be worth at least making `color` without arguments (re)apply the current scheme instead of just reporting it. That way you could at least force a refresh pretty straightforwardly without having to remember or type the name of the scheme.

**Comment by damnskippy** [comment]
Thanks.  FWIW, I wrote up this shell util to that does it.  Just about the only thing worked.  Doing anything else to be less "intrusive" never set the colors correctly.
```
#!/bin/sh
multiple_windows=$(tmux display-message -p '#{session_windows}')
if [ "$multiple_windows" -gt 1 ]; then
    CONF=~/.vim/.base16
    if [ -f $CONF ]; then
        theme=$(sed '1q;d' $CONF)
    else
        return 1
    fi
    pane_origin=$(tmux display-message -p '#I.#P')
    for w in `tmux list-panes -s -F '#I.#P' | uniq -w1`
    do
        tmux split-window -t $w -l 2
        sleep 0.1 # without this pause, sometimes switching fails
        tmux send-keys "color $theme" C-m
        tmux send-keys "exit" C-m
    done
    tmux select-window -t $pane_origin
fi
```
Alternatively, I also added this to the `colors` file.  However the fact that this file is sourced every time a shell is spawned meant I needed this flag `SOURCING_NEW_SHELL` which gets set at the top of the file and reset at the end of the file.  This way this logic only gets invoked when `color` is called to explicitly set a theme.

```
BASE16_CONFIG=~/.vim/.base16
SOURCING_NEW_SHELL=1
[...]
        multiple_windows=$(tmux display-message -p '#{session_windows}')
        if [ $SOURCING_NEW_SHELL -eq 0 -a $multiple_windows -gt 1 ]; then
            pane_origin=$(tmux display-message -p '#I.#P')
            for w in `tmux list-panes -s -F '#I.#P' | uniq -w1`
            do
                tmux split-window -t $w -l 2
                sleep 0.1 # without this pause, sometimes switching fails
                # tmux send-keys "color $" C-m
                tmux send-keys "sh $FILE" C-m
                tmux send-keys "exit" C-m
            done
            # go back to where we started
            tmux select-window -t $pane_origin
        fi
[...]
SOURCING_NEW_SHELL=0
```

On a related note, personally I'm not sure color needs to be set (determining background, luma, source theme, saving config), every time a shell is spawned when this file gets sourced.  Commenting out the anonymous function() at the end of this file to avoid this seemed to speed up the spawning of the shell a bit.  I do understand the need to set the theme automatically based on the config *first* time a shell is spawned in the terminal, although I'm not sure how I would determine that programmatically.

**Comment by damnskippy** [comment]
One other thing I failed to note is that I also used this wonderful logic as a hook to set the theme for FZF as well using:
https://github.com/nicodebo/base16-fzf

Basically added the following after sh $FILE
`source ~/.zsh/base16-fzf/bash/base16-$SCHEME.config`

Thanks very much for all of this.

**Comment by damnskippy** [comment]
> set the theme automatically based on the config first time a shell is spawned in the terminal, although I'm not sure how I would determine that programmatically.

I guess one way to do when running TMUX would be to check for something like this perhaps in colors file.
```
    if [ $(tmux display-message -p '#{session_windows}') -eq 1 -a \
        $(tmux display-message -p '#{window_panes}') -eq 1 ]; then
        [...]
    fi
```
Just a thought.
