### ISSUE TITLE
Discussion: Mac App Store cli tool

### ISSUE THREAD

**Issue by bradwood** [wincent/wincent#73]
Hey Greg,

Have you seen this: https://github.com/mas-cli/mas ?

Might be cool to get it working with MacOSX keychain and linked in as another ansible role...

Having a dig through this now, but just thought I'd mention it...

**Comment by bradwood** [comment]
I guess, after `brew` and now `mas`, you could also go the whole hog with `pip` and `gem` and `apt` etc...

**Comment by wincent** [comment]
> Have you seen this

I tried `mas` a while back, but it wasn't very good at the time, so I removed it in e8a038a78d1444f61b360beae2d9debeb111abcf (December, 2016). In the end I am happy enough installing as much as possible with `brew` and `brew cask`, and leaving a few things handled by the Mac App Store.

**Comment by bradwood** [comment]
Fair enough... I wonder whether it's improved any since 2016... I'll give it a whirl when I can be arsed... and report back.
