### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by mehmetcanbudak** [wincent/wincent#75]
## Expected Behavior
install

## Actual Behavior
install with errors

## Steps to Reproduce the Problem

1. clone the github repo
2. ./install
3. see the errors

## Specifications

- Version: 10.14.3 (18D109)
- Platform: MacOS Mojave
- Subsystem: 

![Screen Shot 2019-03-18 at 18 23 25 (2)](https://user-images.githubusercontent.com/18473037/54541490-19a52780-49ab-11e9-99e4-7800d2b026d2.png)

**Comment by mehmetcanbudak** [comment]
![Screen Shot 2019-03-19 at 15 50 09 (2)](https://user-images.githubusercontent.com/18473037/54607194-d73d2280-4a5e-11e9-938f-6ed12d4a14b1.png)

**Comment by wincent** [comment]
Any chance you could post the text as a gist? Those screenshots are very hard to read.

**Comment by mehmetcanbudak** [comment]
TASK [homebrew : homebrew | bundle] ******************************************************************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["brew", "bundle"], "delta": "0:02:20.195438", "end": "2019-03-19 16:41:38.673604", "msg": "non-zero return code", "rc": 1, "start": "2019-03-19 16:39:18.478166", "stderr": "", "stderr_lines": [], "stdout": "Using caskroom/cask\nUsing homebrew/bundle\nUsing homebrew/core\nUsing homebrew/services\nUsing tavianator/tap\nUsing abook\nUsing ack\nUsing ant\nUsing aspcud\nUsing autoconf\nUsing automake\nUsing awscli\nUsing bdw-gc\nUsing berkeley-db\nUsing cabal-install\nUsing cairo\nUsing camlp4\nUsing chruby\nUsing clasp\nUsing clipper\nUsing cloc\nUsing cloog\nUsing closure-compiler\nUsing cmake\nUsing coreutils\nUsing cscope\nUsing ctags\nUsing elinks\nUsing ffmpeg\nUsing fontconfig\nUsing freetype\nUsing fswatch\nUsing fzf\nUsing gcc\nUsing gd\nUsing gdb\nUsing gdbm\nUsing gdk-pixbuf\nUsing gettext\nUsing ghc\nUsing gifsicle\nUsing git\nUsing glib\nUsing gmime\nUsing gmp\nUsing gnu-sed\nUsing gnupg\nUsing gnupg2\nUsing gnutls\nUsing go\nUsing gobject-introspection\nUsing gringo\nUsing harfbuzz\nUsing highlight\nUsing htop-osx\nUsing httping\nUsing httrack\nUsing hub\nUsing icu4c\nUsing ievms\nUsing iftop\nUsing imagemagick\nUsing imapfilter\nUsing isl\nUsing isync\nUsing jemalloc\nUsing jpeg\nUsing jq\nUsing json-c\nUsing lame\nUsing lbdb\nUsing less\nUsing libassuan\nUsing libcroco\nUsing libevent\nUsing libffi\nUsing libgcrypt\nUsing libgpg-error\nUsing libksba\nUsing libmpc\nUsing libpng\nUsing librsvg\nUsing libtasn1\nUsing libtermkey\nUsing libtiff\nUsing libtool\nUsing libusb\nUsing libusb-compat\nUsing libuv\nUsing libvo-aacenc\nUsing libvterm\nUsing libyaml\nUsing links\nUsing lockrun\nUsing lua\nUsing macvim\nUsing makedepend\nUsing mariadb\nUsing memcached\nUsing mobile-shell\nUsing mpfr\nUsing msgpack\nUsing msmtp\nUsing mutt\nUsing neovim\nUsing nettle\nUsing nginx\nUsing node\nUsing notmuch\nUsing ocaml\nUsing ocamlbuild\nUsing openssl\nUsing openssl@1.1\nUsing optipng\nUsing ossp-uuid\nUsing pandoc\nUsing pango\nUsing par\nUsing parallel\nUsing pcre\nUsing perl\nUsing pinentry\nUsing pixman\nUsing pkg-config\nUsing pngquant\nUsing postgresql\nUsing potrace\nUsing protobuf\nUsing pstree\nUsing pth\nUsing pwgen\nUsing python\nUsing python3\nUsing qemu\nUsing qt\nUsing ragel\nUsing ranger\nUsing readline\nUsing reattach-to-user-namespace\nUsing redis\nUsing rhino\nUsing ripgrep\nUsing ruby-install\nUsing s3cmd\nUsing shared-mime-info\nUsing shellcheck\nUsing sqlite\nUsing talloc\nUsing tavianator/tap/bfs\nUsing terminal-notifier\nUsing the_silver_searcher\nUsing tig\nUsing tmux\nUsing tokyo-cabinet\nUsing tree\nUsing unar\nUsing unibilium\nUsing urlview\nUsing utf8proc\nUsing v8\nUsing vim\nUsing watch\nUsing webp\nUsing wget\nUsing x264\nUsing xapian\nUsing xvid\nUsing xz\nUsing yarn\nUsing zsh\nUsing alfred\nUsing arq\nUsing bartender\nInstalling caskroom/versions/1password-beta\nInstalling caskroom/versions/firefox-developer-edition\nInstalling caskroom/versions/google-chrome-canary\nUsing dropbox\nError: Cask firefox-beta exists in multiple taps:\n  homebrew/cask-versions/firefox-beta\n  caskroom/versions/firefox-beta\nInstalling firefox has failed!\nError: Cask google-chrome-beta exists in multiple taps:\n  homebrew/cask-versions/google-chrome-beta\n  caskroom/versions/google-chrome-beta\nInstalling google-chrome has failed!\nUsing hammerspoon\nUsing isolator\nUsing istat-menus\nError: Cask iterm2-nightly exists in multiple taps:\n  homebrew/cask-versions/iterm2-nightly\n  caskroom/versions/iterm2-nightly\nInstalling iterm2-nightly has failed!\nUsing karabiner-elements\nUsing omnidisksweeper\nUsing skype\n==> Satisfying dependencies\n==> Downloading https://download.scdn.co/Spotify.dmg\n==> No SHA-256 checksum defined for Cask 'spotify', skipping verification.\n==> Installing Cask spotify\nError: It seems there is already an App at '/Applications/Spotify.app'.\n==> Purging files for version latest of Cask spotify\nInstalling spotify has failed!\nUsing steam\n==> Upgrading 1 outdated package:\nsuperduper 3.2.3,116 -> 3.2.4,118\n==> Satisfying dependencies\n==> Downloading https://s3.amazonaws.com/shirtpocket/SuperDuper/SuperDuper!.dmg\nAlready downloaded: /Users/mehmetcanbudak/Library/Caches/Homebrew/downloads/9b49d3c2a9af413c893e095144d039fd4de88cea1928a1a301c5b26b189347b2--SuperDuper!.dmg\nError: It seems the App source '/Applications/SuperDuper!.app' is not there.\n==> Verifying SHA-256 checksum for Cask 'superduper'.\n==> Starting upgrade for Cask superduper\n==> Purging files for version 3.2.4,118 of Cask superduper\nInstalling superduper has failed!\nUsing tcl\nError: Cask transmission-nightly exists in multiple taps:\n  homebrew/cask-versions/transmission-nightly\n  caskroom/versions/transmission-nightly\nInstalling transmission has failed!\nError: Cask vlc-nightly exists in multiple taps:\n  homebrew/cask-versions/vlc-nightly\n  caskroom/versions/vlc-nightly\nInstalling vlc has failed!\nUsing xquartz\nHomebrew Bundle failed! 7 Brewfile dependencies failed to install.", "stdout_lines": ["Using caskroom/cask", "Using homebrew/bundle", "Using homebrew/core", "Using homebrew/services", "Using tavianator/tap", "Using abook", "Using ack", "Using ant", "Using aspcud", "Using autoconf", "Using automake", "Using awscli", "Using bdw-gc", "Using berkeley-db", "Using cabal-install", "Using cairo", "Using camlp4", "Using chruby", "Using clasp", "Using clipper", "Using cloc", "Using cloog", "Using closure-compiler", "Using cmake", "Using coreutils", "Using cscope", "Using ctags", "Using elinks", "Using ffmpeg", "Using fontconfig", "Using freetype", "Using fswatch", "Using fzf", "Using gcc", "Using gd", "Using gdb", "Using gdbm", "Using gdk-pixbuf", "Using gettext", "Using ghc", "Using gifsicle", "Using git", "Using glib", "Using gmime", "Using gmp", "Using gnu-sed", "Using gnupg", "Using gnupg2", "Using gnutls", "Using go", "Using gobject-introspection", "Using gringo", "Using harfbuzz", "Using highlight", "Using htop-osx", "Using httping", "Using httrack", "Using hub", "Using icu4c", "Using ievms", "Using iftop", "Using imagemagick", "Using imapfilter", "Using isl", "Using isync", "Using jemalloc", "Using jpeg", "Using jq", "Using json-c", "Using lame", "Using lbdb", "Using less", "Using libassuan", "Using libcroco", "Using libevent", "Using libffi", "Using libgcrypt", "Using libgpg-error", "Using libksba", "Using libmpc", "Using libpng", "Using librsvg", "Using libtasn1", "Using libtermkey", "Using libtiff", "Using libtool", "Using libusb", "Using libusb-compat", "Using libuv", "Using libvo-aacenc", "Using libvterm", "Using libyaml", "Using links", "Using lockrun", "Using lua", "Using macvim", "Using makedepend", "Using mariadb", "Using memcached", "Using mobile-shell", "Using mpfr", "Using msgpack", "Using msmtp", "Using mutt", "Using neovim", "Using nettle", "Using nginx", "Using node", "Using notmuch", "Using ocaml", "Using ocamlbuild", "Using openssl", "Using openssl@1.1", "Using optipng", "Using ossp-uuid", "Using pandoc", "Using pango", "Using par", "Using parallel", "Using pcre", "Using perl", "Using pinentry", "Using pixman", "Using pkg-config", "Using pngquant", "Using postgresql", "Using potrace", "Using protobuf", "Using pstree", "Using pth", "Using pwgen", "Using python", "Using python3", "Using qemu", "Using qt", "Using ragel", "Using ranger", "Using readline", "Using reattach-to-user-namespace", "Using redis", "Using rhino", "Using ripgrep", "Using ruby-install", "Using s3cmd", "Using shared-mime-info", "Using shellcheck", "Using sqlite", "Using talloc", "Using tavianator/tap/bfs", "Using terminal-notifier", "Using the_silver_searcher", "Using tig", "Using tmux", "Using tokyo-cabinet", "Using tree", "Using unar", "Using unibilium", "Using urlview", "Using utf8proc", "Using v8", "Using vim", "Using watch", "Using webp", "Using wget", "Using x264", "Using xapian", "Using xvid", "Using xz", "Using yarn", "Using zsh", "Using alfred", "Using arq", "Using bartender", "Installing caskroom/versions/1password-beta", "Installing caskroom/versions/firefox-developer-edition", "Installing caskroom/versions/google-chrome-canary", "Using dropbox", "Error: Cask firefox-beta exists in multiple taps:", "  homebrew/cask-versions/firefox-beta", "  caskroom/versions/firefox-beta", "Installing firefox has failed!", "Error: Cask google-chrome-beta exists in multiple taps:", "  homebrew/cask-versions/google-chrome-beta", "  caskroom/versions/google-chrome-beta", "Installing google-chrome has failed!", "Using hammerspoon", "Using isolator", "Using istat-menus", "Error: Cask iterm2-nightly exists in multiple taps:", "  homebrew/cask-versions/iterm2-nightly", "  caskroom/versions/iterm2-nightly", "Installing iterm2-nightly has failed!", "Using karabiner-elements", "Using omnidisksweeper", "Using skype", "==> Satisfying dependencies", "==> Downloading https://download.scdn.co/Spotify.dmg", "==> No SHA-256 checksum defined for Cask 'spotify', skipping verification.", "==> Installing Cask spotify", "Error: It seems there is already an App at '/Applications/Spotify.app'.", "==> Purging files for version latest of Cask spotify", "Installing spotify has failed!", "Using steam", "==> Upgrading 1 outdated package:", "superduper 3.2.3,116 -> 3.2.4,118", "==> Satisfying dependencies", "==> Downloading https://s3.amazonaws.com/shirtpocket/SuperDuper/SuperDuper!.dmg", "Already downloaded: /Users/mehmetcanbudak/Library/Caches/Homebrew/downloads/9b49d3c2a9af413c893e095144d039fd4de88cea1928a1a301c5b26b189347b2--SuperDuper!.dmg", "Error: It seems the App source '/Applications/SuperDuper!.app' is not there.", "==> Verifying SHA-256 checksum for Cask 'superduper'.", "==> Starting upgrade for Cask superduper", "==> Purging files for version 3.2.4,118 of Cask superduper", "Installing superduper has failed!", "Using tcl", "Error: Cask transmission-nightly exists in multiple taps:", "  homebrew/cask-versions/transmission-nightly", "  caskroom/versions/transmission-nightly", "Installing transmission has failed!", "Error: Cask vlc-nightly exists in multiple taps:", "  homebrew/cask-versions/vlc-nightly", "  caskroom/versions/vlc-nightly", "Installing vlc has failed!", "Using xquartz", "Homebrew Bundle failed! 7 Brewfile dependencies failed to install."]}
	to retry, use: --limit @/Users/mehmetcanbudak/.ansible/darwin.retry
  
  
After this error I commented out:

#cask 'firefox'
#cask 'google-chrome' 
#cask 'iterm2-nightly'  
#cask 'spotify'
#cask 'superduper'  
#cask 'transmission'
#cask 'vlc'
#cask 'xquartz'

And now the error is:

TASK [vim : vim | build LanguageClient-neovim] *********************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "./install.sh", "msg": "[Errno 2] No such file or directory", "rc": 2}
	to retry, use: --limit @/Users/mehmetcanbudak/.ansible/darwin.retry

**Comment by wincent** [comment]
> After this error I commented out:
>
> #cask 'firefox'
> #cask 'google-chrome'
> #cask 'iterm2-nightly'
> #cask 'spotify'
> #cask 'superduper'
> #cask 'transmission'
> #cask 'vlc'
> #cask 'xquartz'

Sounds reasonable.

> And now the error is:
> 
>     TASK [vim : vim | build LanguageClient-neovim] *********************************
>     fatal: [localhost]: FAILED! => {"changed": false, "cmd": "./install.sh", "msg": "[Errno 2] No such file or directory", "rc": 2}
>     	to retry, use: --limit @/Users/mehmetcanbudak/.ansible/darwin.retry

This makes me wonder whether all the submodules are updated. There should be an `install.sh` file at `roles/dotfiles/files/.vim/pack/LanguageClient-neovim/opt/LanguageClient-neovim/`. What's in there for you? Also, that submodule should be pointing at the "next" branch (what does `git status` in there say?).

Did you run `git submodule update --init --recursive`? That's a necessary step which I should probably document in the README.

**Comment by wincent** [comment]
(Although the README *does* say to use `git clone --recursive`, which has the same effect.)

**Comment by mehmetcanbudak** [comment]
Hello,

I tried 
git submodule update --init —recursive
Still getting the same error.

--This makes me wonder whether all the submodules are updated. There should be an install.sh file at roles/dotfiles/files/.vim/pack/LanguageClient-neovim/opt/LanguageClient-neovim/. What's in there for you? Also, that submodule should be pointing at the "next" branch (what does git status in there say?).


When I do git status in there I get:

LanguageClient-neovim ❯ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

Please check the attached screenshot for the folder structure. 
There should be an install.sh file at roles/dotfiles/files/.vim/pack/LanguageClient-neovim/opt/LanguageClient-neovim/
There is no install.sh
