### ISSUE TITLE
Pycrypto is unmaintained

### ISSUE THREAD

**Issue by gagbo** [wincent/wincent#77]
Sorry for not using the template, I didn't test anything in your config.

It's just a small heads up as I saw in the readme you're using PyCrypto (and indeed I found a line mentionning [it](https://github.com/wincent/wincent/blob/bddfe001025abff6b945d142dd1305ad7ba0e55a/install#L102) ), but PyCrypto is not maintained anymore (and [hasn't been for a while](https://github.com/dlitz/pycrypto/issues/285)). Using [Pycryptodome](https://github.com/Legrandin/pycryptodome) instead should work as a drop-in replacement.

Cheers

**Comment by wincent** [comment]
Thanks for pointing this out @gagbo.

This came by way of Ansible a long time ago; [their current requirements list](https://github.com/ansible/ansible/blob/24a46deef58d9b21ce4e3dcce3b142e5dd70d722/requirements.txt) mentions `cryptography` and I see that in [commit e238ae999b90b771f662ac15e6cceff8aa0b721f](https://github.com/ansible/ansible/commit/e238ae999b90b771f662ac15e6cceff8aa0b721f#diff-b4ef698db8ca845e5845c4618278f29a) they dropped the `pycrypto` dependency, so I'll remove it.

Trouble is I don't set up brand new machines too often, so the install process only ever really gets tested every few years at best...
