### ISSUE TITLE
"dotfiles" role shouldn't depend on node

### ISSUE THREAD

**Issue by wincent** [wincent/wincent#79]
Copying this over from: https://github.com/wincent/wincent/issues/49#issuecomment-524573913

<blockquote>
I get a fatal error during the full install, I have this message :

```
Fatal: [localhost]: FAILED! => {
    "changed": true, 
    "cmd": [
        "/home/xxxxxxxx/wincent/roles/dotfiles/support/karabiner-test.js"
    ], 
    "delta": "0:00:00.470693", 
    "end": "2019-08-24 21:02:02.314613", 
    "invocation": {
        "module_args": {
            "_raw_params": "/home/xxxxxxxx/wincent/roles/dotfiles/support/karabiner-test.js", 
            "_uses_shell": false, 
            "argv": null, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "stdin": null, 
            "warn": true
        }
    }, 
    "msg": "non-zero return code", 
    "rc": 127, 
    "start": "2019-08-24 21:02:01.843920", 
    "stderr": "/usr/bin/env: ‘node’: No such file or directory", 
    "stderr_lines": [
        "/usr/bin/env: ‘node’: No such file or directory"
    ], 
    "stdout": "", 
    "stdout_lines": []
}
	to retry, use: --limit @/home/xxxxxxxxx/.ansible/linux.retry
```

Im on Manjaro xfce. any idea ?
</blockquote>

**Comment by wincent** [comment]
Two issues here: you shouldn't need node to install the dotfiles, and even if that weren't the case, we shouldn't be trying to install the Karabiner-specific config on non-Darwin platforms.

**Comment by cadens07** [comment]
HI , Thanks,

I'm new in linux, so what I gave to do ?
regards,

**Comment by wincent** [comment]
@cadens07: in you clone of the repo, try:

```shell
git pull
./install dotfiles
```

That will just install some dotfiles.

```shell
./install
```

Would install a bit more (some Vim stuff and some terminfo database entries).

Having said that, if you're new to Linux, I probably wouldn't recommend installing a large set of dotfiles like this, because you won't understand what any of it does. You might be better off coming up with a list of features that you want (like a right-side prompt, or italics in the terminal, or access to the clipboard on remote machines, or some helpful aliases etc) and then start by figuring out how to do each one, one at a time. That's how these dotfiles were built up, one feature at a time, over many years.
