### ISSUE TITLE
[error]   command `brew tap=homebrew/bundle` failed

### ISSUE THREAD

**Issue by mehmetcanbudak** [wincent/wincent#88]
## Steps to Reproduce the Problem

1. ...Clone the repo and ./install

## Specifications

-   Version:10.15.4
-   Platform:MacoOS
-   Subsystem:Catalina
<img width="1920" alt="Screen Shot 2020-05-20 at 4 31 05 AM" src="https://user-images.githubusercontent.com/18473037/82394857-c4532300-9a52-11ea-8153-247a6850db29.png">

**Comment by wincent** [comment]
@mehmetcanbudak: thanks for the report. I'll push a fix with this little diff:

```diff
diff --git a/aspects/homebrew/index.ts b/aspects/homebrew/index.ts
index 1d3e33c8..238b4a0a 100644
--- a/aspects/homebrew/index.ts
+++ b/aspects/homebrew/index.ts
@@ -26,7 +26,7 @@ task('tap "homebrew/bundle"', async () => {
         return skip('already tapped');
     }
 
-    await command('brew', ['tap=homebrew/bundle']);
+    await command('brew', ['tap', 'homebrew/bundle']);
 });
 
 task('prepare Brewfile', async () => {
```

One meta point though: you probably don't want to just run `./install` without any arguments and get *everything* that `install` installs. It's very unlikely you'd want it all. For example, the "homebrew" aspect is going to install a *huge* [list of packages](https://github.com/wincent/wincent/blob/f566f44600a0bd5b774c05330464fd6bb649ae65/aspects/homebrew/templates/Brewfile.erb), many of which are probably totally irrelevant to you (and which Homebrew is probably going to take 30 or 40 minutes to finish installing).

`install` is going to run [all of these aspects](https://github.com/wincent/wincent/blob/f566f44600a0bd5b774c05330464fd6bb649ae65/project.json#L5-L22). One thing you can do is just run selected aspects (eg. `./install dotfiles` or `./install dotfiles vim`). Or you could just look in the dotfiles and steal the individual bits from them (like I said above, it is unlikely that you'd want everything to be exactly like I want it).
