### ISSUE TITLE
Not an Issue, Just Another Conf Repo I Thought You’d Like

### ISSUE THREAD

**Issue by Frizlab** [wincent/wincent#93]
I read somewhere in your doc you like seeing conf repositories, so here’s mine! I install everything using `zsh`; I have literally no dependency on macOS except for the CLT. (I build `ccrypt` on first run directly and use `m4` for the templating, which is builtin on macOS w/ CLT.)
You can close this issue right away 🙃
Cheers

https://github.com/Frizlab/frizlabs-conf

**Comment by wincent** [comment]
Always nice to see other approaches! You've gotten rid of Ansible and gone for simplicity which is nice (I, on the other hand, got rid of Ansible and went for complexity, but mostly for fun — and it's _my_ complexity, not somebody else's). And it's nice to minimize the number of dependencies too.

Thanks for sharing!
