### ISSUE TITLE
Add a method to chose random `colors`-scheme

### ISSUE THREAD

**Issue by miallo** [wincent/wincent#94]
I [adapted](https://github.com/miallo/dotfiles/blob/f0561a151c02a4c58d3fb55d2c8123bab57ad3c0/.config/zsh/colors#L144-L146) your [colors](https://github.com/wincent/wincent/blob/master/aspects/dotfiles/files/.zsh/colors)-script and then I just wanted to explore the themes and so I added `colors rand [pattern]` which (as the name suggests) chooses a random color scheme. Are you interested in this? If not - just close this issue ;)

**Comment by miallo** [comment]
Printing the scheme, as well as the resulting options (`-q`/`--quiet`) of course are optional, but I found it nice to have it print the scheme - otherwise I would often run `colors` without additional parameters to see what the name was

**Comment by wincent** [comment]
I probably wouldn't use this myself (I am so boring I just leave it on the same color scheme for months — or years — on end) but if you wanted to share with others it I'd be happy to accept a PR.

**Comment by wincent** [comment]
Closed by #95.
